//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.239 版自动生成。
// 
#pragma warning disable 1591

namespace QJVRMS.Business.OrderWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderServiceSoap", Namespace="http://tempuri.org/")]
    public partial class OrderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderResourceCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddResourceToOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelResourceFromOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderNotPassReasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderNotPassReasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsOrderAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsOrderAlertAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetOrderReadStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderMessageByOrderIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderMessageStatusUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderMessageStatusAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsOrderMessageAlertAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsOrderMessageAlertUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrderService() {
            this.Url = global::QJVRMS.Business.Properties.Settings.Default.QJVRMS_Business_OrderWS_OrderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event GetOrdersByUserIdCompletedEventHandler GetOrdersByUserIdCompleted;
        
        /// <remarks/>
        public event GetOrdersByIdCompletedEventHandler GetOrdersByIdCompleted;
        
        /// <remarks/>
        public event GetOrderResourceCountCompletedEventHandler GetOrderResourceCountCompleted;
        
        /// <remarks/>
        public event UpdateStatusCompletedEventHandler UpdateStatusCompleted;
        
        /// <remarks/>
        public event AddResourceToOrdersCompletedEventHandler AddResourceToOrdersCompleted;
        
        /// <remarks/>
        public event DelResourceFromOrdersCompletedEventHandler DelResourceFromOrdersCompleted;
        
        /// <remarks/>
        public event AddOrderNotPassReasonCompletedEventHandler AddOrderNotPassReasonCompleted;
        
        /// <remarks/>
        public event GetOrderNotPassReasonCompletedEventHandler GetOrderNotPassReasonCompleted;
        
        /// <remarks/>
        public event GetOrderStatusCompletedEventHandler GetOrderStatusCompleted;
        
        /// <remarks/>
        public event IsOrderAlertCompletedEventHandler IsOrderAlertCompleted;
        
        /// <remarks/>
        public event IsOrderAlertAdminCompletedEventHandler IsOrderAlertAdminCompleted;
        
        /// <remarks/>
        public event SetOrderReadStatusCompletedEventHandler SetOrderReadStatusCompleted;
        
        /// <remarks/>
        public event ShowOrdersCompletedEventHandler ShowOrdersCompleted;
        
        /// <remarks/>
        public event AddOrderMessageCompletedEventHandler AddOrderMessageCompleted;
        
        /// <remarks/>
        public event GetOrderMessageByOrderIdCompletedEventHandler GetOrderMessageByOrderIdCompleted;
        
        /// <remarks/>
        public event UpdateOrderMessageStatusUserCompletedEventHandler UpdateOrderMessageStatusUserCompleted;
        
        /// <remarks/>
        public event UpdateOrderMessageStatusAdminCompletedEventHandler UpdateOrderMessageStatusAdminCompleted;
        
        /// <remarks/>
        public event IsOrderMessageAlertAdminCompletedEventHandler IsOrderMessageAlertAdminCompleted;
        
        /// <remarks/>
        public event IsOrderMessageAlertUserCompletedEventHandler IsOrderMessageAlertUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Add(string title, System.DateTime requestDate, int requestSize, string usage, string contents, int status, string userId, string userName) {
            this.Invoke("Add", new object[] {
                        title,
                        requestDate,
                        requestSize,
                        usage,
                        contents,
                        status,
                        userId,
                        userName});
        }
        
        /// <remarks/>
        public void AddAsync(string title, System.DateTime requestDate, int requestSize, string usage, string contents, int status, string userId, string userName) {
            this.AddAsync(title, requestDate, requestSize, usage, contents, status, userId, userName, null);
        }
        
        /// <remarks/>
        public void AddAsync(string title, System.DateTime requestDate, int requestSize, string usage, string contents, int status, string userId, string userName, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        title,
                        requestDate,
                        requestSize,
                        usage,
                        contents,
                        status,
                        userId,
                        userName}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrdersByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrdersByUserId(string userId, int PageSize, int PageNum, System.DateTime startDate, System.DateTime endDate, int status) {
            object[] results = this.Invoke("GetOrdersByUserId", new object[] {
                        userId,
                        PageSize,
                        PageNum,
                        startDate,
                        endDate,
                        status});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersByUserIdAsync(string userId, int PageSize, int PageNum, System.DateTime startDate, System.DateTime endDate, int status) {
            this.GetOrdersByUserIdAsync(userId, PageSize, PageNum, startDate, endDate, status, null);
        }
        
        /// <remarks/>
        public void GetOrdersByUserIdAsync(string userId, int PageSize, int PageNum, System.DateTime startDate, System.DateTime endDate, int status, object userState) {
            if ((this.GetOrdersByUserIdOperationCompleted == null)) {
                this.GetOrdersByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetOrdersByUserId", new object[] {
                        userId,
                        PageSize,
                        PageNum,
                        startDate,
                        endDate,
                        status}, this.GetOrdersByUserIdOperationCompleted, userState);
        }
        
        private void OnGetOrdersByUserIdOperationCompleted(object arg) {
            if ((this.GetOrdersByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersByUserIdCompleted(this, new GetOrdersByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrdersById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrdersById(string id) {
            object[] results = this.Invoke("GetOrdersById", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersByIdAsync(string id) {
            this.GetOrdersByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOrdersByIdAsync(string id, object userState) {
            if ((this.GetOrdersByIdOperationCompleted == null)) {
                this.GetOrdersByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersByIdOperationCompleted);
            }
            this.InvokeAsync("GetOrdersById", new object[] {
                        id}, this.GetOrdersByIdOperationCompleted, userState);
        }
        
        private void OnGetOrdersByIdOperationCompleted(object arg) {
            if ((this.GetOrdersByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersByIdCompleted(this, new GetOrdersByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderResourceCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetOrderResourceCount(string id) {
            object[] results = this.Invoke("GetOrderResourceCount", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderResourceCountAsync(string id) {
            this.GetOrderResourceCountAsync(id, null);
        }
        
        /// <remarks/>
        public void GetOrderResourceCountAsync(string id, object userState) {
            if ((this.GetOrderResourceCountOperationCompleted == null)) {
                this.GetOrderResourceCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderResourceCountOperationCompleted);
            }
            this.InvokeAsync("GetOrderResourceCount", new object[] {
                        id}, this.GetOrderResourceCountOperationCompleted, userState);
        }
        
        private void OnGetOrderResourceCountOperationCompleted(object arg) {
            if ((this.GetOrderResourceCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderResourceCountCompleted(this, new GetOrderResourceCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateStatus(string id, int status) {
            object[] results = this.Invoke("UpdateStatus", new object[] {
                        id,
                        status});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string id, int status) {
            this.UpdateStatusAsync(id, status, null);
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string id, int status, object userState) {
            if ((this.UpdateStatusOperationCompleted == null)) {
                this.UpdateStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateStatus", new object[] {
                        id,
                        status}, this.UpdateStatusOperationCompleted, userState);
        }
        
        private void OnUpdateStatusOperationCompleted(object arg) {
            if ((this.UpdateStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusCompleted(this, new UpdateStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddResourceToOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddResourceToOrders(string orderid, string[] resourceIds) {
            this.Invoke("AddResourceToOrders", new object[] {
                        orderid,
                        resourceIds});
        }
        
        /// <remarks/>
        public void AddResourceToOrdersAsync(string orderid, string[] resourceIds) {
            this.AddResourceToOrdersAsync(orderid, resourceIds, null);
        }
        
        /// <remarks/>
        public void AddResourceToOrdersAsync(string orderid, string[] resourceIds, object userState) {
            if ((this.AddResourceToOrdersOperationCompleted == null)) {
                this.AddResourceToOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddResourceToOrdersOperationCompleted);
            }
            this.InvokeAsync("AddResourceToOrders", new object[] {
                        orderid,
                        resourceIds}, this.AddResourceToOrdersOperationCompleted, userState);
        }
        
        private void OnAddResourceToOrdersOperationCompleted(object arg) {
            if ((this.AddResourceToOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddResourceToOrdersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelResourceFromOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DelResourceFromOrders(string orderId, string resourceId) {
            object[] results = this.Invoke("DelResourceFromOrders", new object[] {
                        orderId,
                        resourceId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DelResourceFromOrdersAsync(string orderId, string resourceId) {
            this.DelResourceFromOrdersAsync(orderId, resourceId, null);
        }
        
        /// <remarks/>
        public void DelResourceFromOrdersAsync(string orderId, string resourceId, object userState) {
            if ((this.DelResourceFromOrdersOperationCompleted == null)) {
                this.DelResourceFromOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelResourceFromOrdersOperationCompleted);
            }
            this.InvokeAsync("DelResourceFromOrders", new object[] {
                        orderId,
                        resourceId}, this.DelResourceFromOrdersOperationCompleted, userState);
        }
        
        private void OnDelResourceFromOrdersOperationCompleted(object arg) {
            if ((this.DelResourceFromOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelResourceFromOrdersCompleted(this, new DelResourceFromOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrderNotPassReason", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddOrderNotPassReason(string orderId, string reason) {
            object[] results = this.Invoke("AddOrderNotPassReason", new object[] {
                        orderId,
                        reason});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrderNotPassReasonAsync(string orderId, string reason) {
            this.AddOrderNotPassReasonAsync(orderId, reason, null);
        }
        
        /// <remarks/>
        public void AddOrderNotPassReasonAsync(string orderId, string reason, object userState) {
            if ((this.AddOrderNotPassReasonOperationCompleted == null)) {
                this.AddOrderNotPassReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderNotPassReasonOperationCompleted);
            }
            this.InvokeAsync("AddOrderNotPassReason", new object[] {
                        orderId,
                        reason}, this.AddOrderNotPassReasonOperationCompleted, userState);
        }
        
        private void OnAddOrderNotPassReasonOperationCompleted(object arg) {
            if ((this.AddOrderNotPassReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderNotPassReasonCompleted(this, new AddOrderNotPassReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderNotPassReason", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOrderNotPassReason(string orderId) {
            object[] results = this.Invoke("GetOrderNotPassReason", new object[] {
                        orderId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderNotPassReasonAsync(string orderId) {
            this.GetOrderNotPassReasonAsync(orderId, null);
        }
        
        /// <remarks/>
        public void GetOrderNotPassReasonAsync(string orderId, object userState) {
            if ((this.GetOrderNotPassReasonOperationCompleted == null)) {
                this.GetOrderNotPassReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderNotPassReasonOperationCompleted);
            }
            this.InvokeAsync("GetOrderNotPassReason", new object[] {
                        orderId}, this.GetOrderNotPassReasonOperationCompleted, userState);
        }
        
        private void OnGetOrderNotPassReasonOperationCompleted(object arg) {
            if ((this.GetOrderNotPassReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderNotPassReasonCompleted(this, new GetOrderNotPassReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrderStatus(System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("GetOrderStatus", new object[] {
                        startDate,
                        endDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderStatusAsync(System.DateTime startDate, System.DateTime endDate) {
            this.GetOrderStatusAsync(startDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetOrderStatusAsync(System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.GetOrderStatusOperationCompleted == null)) {
                this.GetOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderStatusOperationCompleted);
            }
            this.InvokeAsync("GetOrderStatus", new object[] {
                        startDate,
                        endDate}, this.GetOrderStatusOperationCompleted, userState);
        }
        
        private void OnGetOrderStatusOperationCompleted(object arg) {
            if ((this.GetOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderStatusCompleted(this, new GetOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsOrderAlert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsOrderAlert(System.Guid userId) {
            object[] results = this.Invoke("IsOrderAlert", new object[] {
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsOrderAlertAsync(System.Guid userId) {
            this.IsOrderAlertAsync(userId, null);
        }
        
        /// <remarks/>
        public void IsOrderAlertAsync(System.Guid userId, object userState) {
            if ((this.IsOrderAlertOperationCompleted == null)) {
                this.IsOrderAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsOrderAlertOperationCompleted);
            }
            this.InvokeAsync("IsOrderAlert", new object[] {
                        userId}, this.IsOrderAlertOperationCompleted, userState);
        }
        
        private void OnIsOrderAlertOperationCompleted(object arg) {
            if ((this.IsOrderAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsOrderAlertCompleted(this, new IsOrderAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsOrderAlertAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsOrderAlertAdmin(System.Guid userId) {
            object[] results = this.Invoke("IsOrderAlertAdmin", new object[] {
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsOrderAlertAdminAsync(System.Guid userId) {
            this.IsOrderAlertAdminAsync(userId, null);
        }
        
        /// <remarks/>
        public void IsOrderAlertAdminAsync(System.Guid userId, object userState) {
            if ((this.IsOrderAlertAdminOperationCompleted == null)) {
                this.IsOrderAlertAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsOrderAlertAdminOperationCompleted);
            }
            this.InvokeAsync("IsOrderAlertAdmin", new object[] {
                        userId}, this.IsOrderAlertAdminOperationCompleted, userState);
        }
        
        private void OnIsOrderAlertAdminOperationCompleted(object arg) {
            if ((this.IsOrderAlertAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsOrderAlertAdminCompleted(this, new IsOrderAlertAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetOrderReadStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetOrderReadStatus(System.Guid userId) {
            this.Invoke("SetOrderReadStatus", new object[] {
                        userId});
        }
        
        /// <remarks/>
        public void SetOrderReadStatusAsync(System.Guid userId) {
            this.SetOrderReadStatusAsync(userId, null);
        }
        
        /// <remarks/>
        public void SetOrderReadStatusAsync(System.Guid userId, object userState) {
            if ((this.SetOrderReadStatusOperationCompleted == null)) {
                this.SetOrderReadStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetOrderReadStatusOperationCompleted);
            }
            this.InvokeAsync("SetOrderReadStatus", new object[] {
                        userId}, this.SetOrderReadStatusOperationCompleted, userState);
        }
        
        private void OnSetOrderReadStatusOperationCompleted(object arg) {
            if ((this.SetOrderReadStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetOrderReadStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ShowOrders(string userName) {
            object[] results = this.Invoke("ShowOrders", new object[] {
                        userName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ShowOrdersAsync(string userName) {
            this.ShowOrdersAsync(userName, null);
        }
        
        /// <remarks/>
        public void ShowOrdersAsync(string userName, object userState) {
            if ((this.ShowOrdersOperationCompleted == null)) {
                this.ShowOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowOrdersOperationCompleted);
            }
            this.InvokeAsync("ShowOrders", new object[] {
                        userName}, this.ShowOrdersOperationCompleted, userState);
        }
        
        private void OnShowOrdersOperationCompleted(object arg) {
            if ((this.ShowOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowOrdersCompleted(this, new ShowOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrderMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddOrderMessage(System.Guid id, System.Guid orderId, string contents, System.DateTime adddate, string userName, int isUserRead, int isAdminRead) {
            object[] results = this.Invoke("AddOrderMessage", new object[] {
                        id,
                        orderId,
                        contents,
                        adddate,
                        userName,
                        isUserRead,
                        isAdminRead});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrderMessageAsync(System.Guid id, System.Guid orderId, string contents, System.DateTime adddate, string userName, int isUserRead, int isAdminRead) {
            this.AddOrderMessageAsync(id, orderId, contents, adddate, userName, isUserRead, isAdminRead, null);
        }
        
        /// <remarks/>
        public void AddOrderMessageAsync(System.Guid id, System.Guid orderId, string contents, System.DateTime adddate, string userName, int isUserRead, int isAdminRead, object userState) {
            if ((this.AddOrderMessageOperationCompleted == null)) {
                this.AddOrderMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderMessageOperationCompleted);
            }
            this.InvokeAsync("AddOrderMessage", new object[] {
                        id,
                        orderId,
                        contents,
                        adddate,
                        userName,
                        isUserRead,
                        isAdminRead}, this.AddOrderMessageOperationCompleted, userState);
        }
        
        private void OnAddOrderMessageOperationCompleted(object arg) {
            if ((this.AddOrderMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderMessageCompleted(this, new AddOrderMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderMessageByOrderId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderMessageByOrderId(System.Guid orderId) {
            object[] results = this.Invoke("GetOrderMessageByOrderId", new object[] {
                        orderId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderMessageByOrderIdAsync(System.Guid orderId) {
            this.GetOrderMessageByOrderIdAsync(orderId, null);
        }
        
        /// <remarks/>
        public void GetOrderMessageByOrderIdAsync(System.Guid orderId, object userState) {
            if ((this.GetOrderMessageByOrderIdOperationCompleted == null)) {
                this.GetOrderMessageByOrderIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderMessageByOrderIdOperationCompleted);
            }
            this.InvokeAsync("GetOrderMessageByOrderId", new object[] {
                        orderId}, this.GetOrderMessageByOrderIdOperationCompleted, userState);
        }
        
        private void OnGetOrderMessageByOrderIdOperationCompleted(object arg) {
            if ((this.GetOrderMessageByOrderIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderMessageByOrderIdCompleted(this, new GetOrderMessageByOrderIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderMessageStatusUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateOrderMessageStatusUser(System.Guid orderId, int isRead) {
            object[] results = this.Invoke("UpdateOrderMessageStatusUser", new object[] {
                        orderId,
                        isRead});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderMessageStatusUserAsync(System.Guid orderId, int isRead) {
            this.UpdateOrderMessageStatusUserAsync(orderId, isRead, null);
        }
        
        /// <remarks/>
        public void UpdateOrderMessageStatusUserAsync(System.Guid orderId, int isRead, object userState) {
            if ((this.UpdateOrderMessageStatusUserOperationCompleted == null)) {
                this.UpdateOrderMessageStatusUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderMessageStatusUserOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderMessageStatusUser", new object[] {
                        orderId,
                        isRead}, this.UpdateOrderMessageStatusUserOperationCompleted, userState);
        }
        
        private void OnUpdateOrderMessageStatusUserOperationCompleted(object arg) {
            if ((this.UpdateOrderMessageStatusUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderMessageStatusUserCompleted(this, new UpdateOrderMessageStatusUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderMessageStatusAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateOrderMessageStatusAdmin(System.Guid orderId, int isRead) {
            object[] results = this.Invoke("UpdateOrderMessageStatusAdmin", new object[] {
                        orderId,
                        isRead});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderMessageStatusAdminAsync(System.Guid orderId, int isRead) {
            this.UpdateOrderMessageStatusAdminAsync(orderId, isRead, null);
        }
        
        /// <remarks/>
        public void UpdateOrderMessageStatusAdminAsync(System.Guid orderId, int isRead, object userState) {
            if ((this.UpdateOrderMessageStatusAdminOperationCompleted == null)) {
                this.UpdateOrderMessageStatusAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderMessageStatusAdminOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderMessageStatusAdmin", new object[] {
                        orderId,
                        isRead}, this.UpdateOrderMessageStatusAdminOperationCompleted, userState);
        }
        
        private void OnUpdateOrderMessageStatusAdminOperationCompleted(object arg) {
            if ((this.UpdateOrderMessageStatusAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderMessageStatusAdminCompleted(this, new UpdateOrderMessageStatusAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsOrderMessageAlertAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IsOrderMessageAlertAdmin() {
            object[] results = this.Invoke("IsOrderMessageAlertAdmin", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IsOrderMessageAlertAdminAsync() {
            this.IsOrderMessageAlertAdminAsync(null);
        }
        
        /// <remarks/>
        public void IsOrderMessageAlertAdminAsync(object userState) {
            if ((this.IsOrderMessageAlertAdminOperationCompleted == null)) {
                this.IsOrderMessageAlertAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsOrderMessageAlertAdminOperationCompleted);
            }
            this.InvokeAsync("IsOrderMessageAlertAdmin", new object[0], this.IsOrderMessageAlertAdminOperationCompleted, userState);
        }
        
        private void OnIsOrderMessageAlertAdminOperationCompleted(object arg) {
            if ((this.IsOrderMessageAlertAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsOrderMessageAlertAdminCompleted(this, new IsOrderMessageAlertAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsOrderMessageAlertUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable IsOrderMessageAlertUser(System.Guid userId) {
            object[] results = this.Invoke("IsOrderMessageAlertUser", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void IsOrderMessageAlertUserAsync(System.Guid userId) {
            this.IsOrderMessageAlertUserAsync(userId, null);
        }
        
        /// <remarks/>
        public void IsOrderMessageAlertUserAsync(System.Guid userId, object userState) {
            if ((this.IsOrderMessageAlertUserOperationCompleted == null)) {
                this.IsOrderMessageAlertUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsOrderMessageAlertUserOperationCompleted);
            }
            this.InvokeAsync("IsOrderMessageAlertUser", new object[] {
                        userId}, this.IsOrderMessageAlertUserOperationCompleted, userState);
        }
        
        private void OnIsOrderMessageAlertUserOperationCompleted(object arg) {
            if ((this.IsOrderMessageAlertUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsOrderMessageAlertUserCompleted(this, new IsOrderMessageAlertUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrdersByUserIdCompletedEventHandler(object sender, GetOrdersByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrdersByIdCompletedEventHandler(object sender, GetOrdersByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderResourceCountCompletedEventHandler(object sender, GetOrderResourceCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderResourceCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderResourceCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateStatusCompletedEventHandler(object sender, UpdateStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddResourceToOrdersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DelResourceFromOrdersCompletedEventHandler(object sender, DelResourceFromOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelResourceFromOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelResourceFromOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddOrderNotPassReasonCompletedEventHandler(object sender, AddOrderNotPassReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrderNotPassReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrderNotPassReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderNotPassReasonCompletedEventHandler(object sender, GetOrderNotPassReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderNotPassReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderNotPassReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderStatusCompletedEventHandler(object sender, GetOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsOrderAlertCompletedEventHandler(object sender, IsOrderAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsOrderAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsOrderAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsOrderAlertAdminCompletedEventHandler(object sender, IsOrderAlertAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsOrderAlertAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsOrderAlertAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetOrderReadStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ShowOrdersCompletedEventHandler(object sender, ShowOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddOrderMessageCompletedEventHandler(object sender, AddOrderMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrderMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrderMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderMessageByOrderIdCompletedEventHandler(object sender, GetOrderMessageByOrderIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderMessageByOrderIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderMessageByOrderIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateOrderMessageStatusUserCompletedEventHandler(object sender, UpdateOrderMessageStatusUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderMessageStatusUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderMessageStatusUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateOrderMessageStatusAdminCompletedEventHandler(object sender, UpdateOrderMessageStatusAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderMessageStatusAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderMessageStatusAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsOrderMessageAlertAdminCompletedEventHandler(object sender, IsOrderMessageAlertAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsOrderMessageAlertAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsOrderMessageAlertAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsOrderMessageAlertUserCompletedEventHandler(object sender, IsOrderMessageAlertUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsOrderMessageAlertUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsOrderMessageAlertUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591