//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.239 版自动生成。
// 
#pragma warning disable 1591

namespace QJVRMS.Business.SearchWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchServiceSoap", Namespace="http://qjDataAccess.org/")]
    public partial class SearchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchService() {
            this.Url = global::QJVRMS.Business.Properties.Settings.Default.QJVRMS_Business_SearchWS_SearchService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchVideoCompletedEventHandler SearchVideoCompleted;
        
        /// <remarks/>
        public event SearchImageCompletedEventHandler SearchImageCompleted;
        
        /// <remarks/>
        public event SearchByDeptCompletedEventHandler SearchByDeptCompleted;
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/SearchVideo", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SearchVideo(string keyword, string beginDate, string endDate, string Catalogid, string Userid, int PageSize, int PageNum, ref int rowCount) {
            object[] results = this.Invoke("SearchVideo", new object[] {
                        keyword,
                        beginDate,
                        endDate,
                        Catalogid,
                        Userid,
                        PageSize,
                        PageNum,
                        rowCount});
            rowCount = ((int)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchVideoAsync(string keyword, string beginDate, string endDate, string Catalogid, string Userid, int PageSize, int PageNum, int rowCount) {
            this.SearchVideoAsync(keyword, beginDate, endDate, Catalogid, Userid, PageSize, PageNum, rowCount, null);
        }
        
        /// <remarks/>
        public void SearchVideoAsync(string keyword, string beginDate, string endDate, string Catalogid, string Userid, int PageSize, int PageNum, int rowCount, object userState) {
            if ((this.SearchVideoOperationCompleted == null)) {
                this.SearchVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchVideoOperationCompleted);
            }
            this.InvokeAsync("SearchVideo", new object[] {
                        keyword,
                        beginDate,
                        endDate,
                        Catalogid,
                        Userid,
                        PageSize,
                        PageNum,
                        rowCount}, this.SearchVideoOperationCompleted, userState);
        }
        
        private void OnSearchVideoOperationCompleted(object arg) {
            if ((this.SearchVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchVideoCompleted(this, new SearchVideoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/SearchImage", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SearchImage(string keyword, string beginDate, string endDate, string Catalogid, string Userid, int PageSize, int PageNum, ref int rowCount) {
            object[] results = this.Invoke("SearchImage", new object[] {
                        keyword,
                        beginDate,
                        endDate,
                        Catalogid,
                        Userid,
                        PageSize,
                        PageNum,
                        rowCount});
            rowCount = ((int)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchImageAsync(string keyword, string beginDate, string endDate, string Catalogid, string Userid, int PageSize, int PageNum, int rowCount) {
            this.SearchImageAsync(keyword, beginDate, endDate, Catalogid, Userid, PageSize, PageNum, rowCount, null);
        }
        
        /// <remarks/>
        public void SearchImageAsync(string keyword, string beginDate, string endDate, string Catalogid, string Userid, int PageSize, int PageNum, int rowCount, object userState) {
            if ((this.SearchImageOperationCompleted == null)) {
                this.SearchImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchImageOperationCompleted);
            }
            this.InvokeAsync("SearchImage", new object[] {
                        keyword,
                        beginDate,
                        endDate,
                        Catalogid,
                        Userid,
                        PageSize,
                        PageNum,
                        rowCount}, this.SearchImageOperationCompleted, userState);
        }
        
        private void OnSearchImageOperationCompleted(object arg) {
            if ((this.SearchImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchImageCompleted(this, new SearchImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/SearchByDept", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchByDept(System.Guid catalogId, System.Guid userId, System.Guid deptID, int pageSize, int pageIndex) {
            object[] results = this.Invoke("SearchByDept", new object[] {
                        catalogId,
                        userId,
                        deptID,
                        pageSize,
                        pageIndex});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByDeptAsync(System.Guid catalogId, System.Guid userId, System.Guid deptID, int pageSize, int pageIndex) {
            this.SearchByDeptAsync(catalogId, userId, deptID, pageSize, pageIndex, null);
        }
        
        /// <remarks/>
        public void SearchByDeptAsync(System.Guid catalogId, System.Guid userId, System.Guid deptID, int pageSize, int pageIndex, object userState) {
            if ((this.SearchByDeptOperationCompleted == null)) {
                this.SearchByDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByDeptOperationCompleted);
            }
            this.InvokeAsync("SearchByDept", new object[] {
                        catalogId,
                        userId,
                        deptID,
                        pageSize,
                        pageIndex}, this.SearchByDeptOperationCompleted, userState);
        }
        
        private void OnSearchByDeptOperationCompleted(object arg) {
            if ((this.SearchByDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByDeptCompleted(this, new SearchByDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/Search", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Search(string sqlWhere, System.Guid userId, int pageIndex, int pageSize) {
            object[] results = this.Invoke("Search", new object[] {
                        sqlWhere,
                        userId,
                        pageIndex,
                        pageSize});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string sqlWhere, System.Guid userId, int pageIndex, int pageSize) {
            this.SearchAsync(sqlWhere, userId, pageIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string sqlWhere, System.Guid userId, int pageIndex, int pageSize, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        sqlWhere,
                        userId,
                        pageIndex,
                        pageSize}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchVideoCompletedEventHandler(object sender, SearchVideoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchVideoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchVideoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int rowCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchImageCompletedEventHandler(object sender, SearchImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int rowCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchByDeptCompletedEventHandler(object sender, SearchByDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591