//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.239 版自动生成。
// 
#pragma warning disable 1591

namespace QJVRMS.Business.GroupWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GroupServiceSoap", Namespace="http://qjDataAccess.org/")]
    public partial class GroupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateChildGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRootGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByGroupIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchUsers1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupUsersStatOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupIdByGroupNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GroupService() {
            this.Url = global::QJVRMS.Business.Properties.Settings.Default.QJVRMS_Business_GroupWS_GroupService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetGroupCompletedEventHandler GetGroupCompleted;
        
        /// <remarks/>
        public event CreateGroupCompletedEventHandler CreateGroupCompleted;
        
        /// <remarks/>
        public event CreateChildGroupCompletedEventHandler CreateChildGroupCompleted;
        
        /// <remarks/>
        public event DeleteGroupCompletedEventHandler DeleteGroupCompleted;
        
        /// <remarks/>
        public event ModifyGroupCompletedEventHandler ModifyGroupCompleted;
        
        /// <remarks/>
        public event GetTopGroupCompletedEventHandler GetTopGroupCompleted;
        
        /// <remarks/>
        public event GetChildGroupCompletedEventHandler GetChildGroupCompleted;
        
        /// <remarks/>
        public event GetRootGroupCompletedEventHandler GetRootGroupCompleted;
        
        /// <remarks/>
        public event SearchGroupCompletedEventHandler SearchGroupCompleted;
        
        /// <remarks/>
        public event GetGroupListCompletedEventHandler GetGroupListCompleted;
        
        /// <remarks/>
        public event GetUsersByGroupIdCompletedEventHandler GetUsersByGroupIdCompleted;
        
        /// <remarks/>
        public event SearchUsersCompletedEventHandler SearchUsersCompleted;
        
        /// <remarks/>
        public event SearchUsers1CompletedEventHandler SearchUsers1Completed;
        
        /// <remarks/>
        public event GetGroupUsersStatCompletedEventHandler GetGroupUsersStatCompleted;
        
        /// <remarks/>
        public event GetAllGroupsCompletedEventHandler GetAllGroupsCompleted;
        
        /// <remarks/>
        public event GetGroupIdByGroupNameCompletedEventHandler GetGroupIdByGroupNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGroup(System.Guid groupId) {
            object[] results = this.Invoke("GetGroup", new object[] {
                        groupId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupAsync(System.Guid groupId) {
            this.GetGroupAsync(groupId, null);
        }
        
        /// <remarks/>
        public void GetGroupAsync(System.Guid groupId, object userState) {
            if ((this.GetGroupOperationCompleted == null)) {
                this.GetGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupOperationCompleted);
            }
            this.InvokeAsync("GetGroup", new object[] {
                        groupId}, this.GetGroupOperationCompleted, userState);
        }
        
        private void OnGetGroupOperationCompleted(object arg) {
            if ((this.GetGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupCompleted(this, new GetGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/CreateGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid CreateGroup(string groupName, string description) {
            object[] results = this.Invoke("CreateGroup", new object[] {
                        groupName,
                        description});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void CreateGroupAsync(string groupName, string description) {
            this.CreateGroupAsync(groupName, description, null);
        }
        
        /// <remarks/>
        public void CreateGroupAsync(string groupName, string description, object userState) {
            if ((this.CreateGroupOperationCompleted == null)) {
                this.CreateGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGroupOperationCompleted);
            }
            this.InvokeAsync("CreateGroup", new object[] {
                        groupName,
                        description}, this.CreateGroupOperationCompleted, userState);
        }
        
        private void OnCreateGroupOperationCompleted(object arg) {
            if ((this.CreateGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateGroupCompleted(this, new CreateGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/CreateChildGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid CreateChildGroup(System.Guid parentId, string groupName, int orderFlag) {
            object[] results = this.Invoke("CreateChildGroup", new object[] {
                        parentId,
                        groupName,
                        orderFlag});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void CreateChildGroupAsync(System.Guid parentId, string groupName, int orderFlag) {
            this.CreateChildGroupAsync(parentId, groupName, orderFlag, null);
        }
        
        /// <remarks/>
        public void CreateChildGroupAsync(System.Guid parentId, string groupName, int orderFlag, object userState) {
            if ((this.CreateChildGroupOperationCompleted == null)) {
                this.CreateChildGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateChildGroupOperationCompleted);
            }
            this.InvokeAsync("CreateChildGroup", new object[] {
                        parentId,
                        groupName,
                        orderFlag}, this.CreateChildGroupOperationCompleted, userState);
        }
        
        private void OnCreateChildGroupOperationCompleted(object arg) {
            if ((this.CreateChildGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateChildGroupCompleted(this, new CreateChildGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/DeleteGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteGroup(System.Guid groupId) {
            object[] results = this.Invoke("DeleteGroup", new object[] {
                        groupId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteGroupAsync(System.Guid groupId) {
            this.DeleteGroupAsync(groupId, null);
        }
        
        /// <remarks/>
        public void DeleteGroupAsync(System.Guid groupId, object userState) {
            if ((this.DeleteGroupOperationCompleted == null)) {
                this.DeleteGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGroupOperationCompleted);
            }
            this.InvokeAsync("DeleteGroup", new object[] {
                        groupId}, this.DeleteGroupOperationCompleted, userState);
        }
        
        private void OnDeleteGroupOperationCompleted(object arg) {
            if ((this.DeleteGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteGroupCompleted(this, new DeleteGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/ModifyGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModifyGroup(System.Guid groupId, string groupName, int orderFlag) {
            object[] results = this.Invoke("ModifyGroup", new object[] {
                        groupId,
                        groupName,
                        orderFlag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyGroupAsync(System.Guid groupId, string groupName, int orderFlag) {
            this.ModifyGroupAsync(groupId, groupName, orderFlag, null);
        }
        
        /// <remarks/>
        public void ModifyGroupAsync(System.Guid groupId, string groupName, int orderFlag, object userState) {
            if ((this.ModifyGroupOperationCompleted == null)) {
                this.ModifyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyGroupOperationCompleted);
            }
            this.InvokeAsync("ModifyGroup", new object[] {
                        groupId,
                        groupName,
                        orderFlag}, this.ModifyGroupOperationCompleted, userState);
        }
        
        private void OnModifyGroupOperationCompleted(object arg) {
            if ((this.ModifyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyGroupCompleted(this, new ModifyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetTopGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTopGroup() {
            object[] results = this.Invoke("GetTopGroup", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopGroupAsync() {
            this.GetTopGroupAsync(null);
        }
        
        /// <remarks/>
        public void GetTopGroupAsync(object userState) {
            if ((this.GetTopGroupOperationCompleted == null)) {
                this.GetTopGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopGroupOperationCompleted);
            }
            this.InvokeAsync("GetTopGroup", new object[0], this.GetTopGroupOperationCompleted, userState);
        }
        
        private void OnGetTopGroupOperationCompleted(object arg) {
            if ((this.GetTopGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopGroupCompleted(this, new GetTopGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetChildGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetChildGroup(System.Guid parentId) {
            object[] results = this.Invoke("GetChildGroup", new object[] {
                        parentId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetChildGroupAsync(System.Guid parentId) {
            this.GetChildGroupAsync(parentId, null);
        }
        
        /// <remarks/>
        public void GetChildGroupAsync(System.Guid parentId, object userState) {
            if ((this.GetChildGroupOperationCompleted == null)) {
                this.GetChildGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildGroupOperationCompleted);
            }
            this.InvokeAsync("GetChildGroup", new object[] {
                        parentId}, this.GetChildGroupOperationCompleted, userState);
        }
        
        private void OnGetChildGroupOperationCompleted(object arg) {
            if ((this.GetChildGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildGroupCompleted(this, new GetChildGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetRootGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRootGroup() {
            object[] results = this.Invoke("GetRootGroup", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRootGroupAsync() {
            this.GetRootGroupAsync(null);
        }
        
        /// <remarks/>
        public void GetRootGroupAsync(object userState) {
            if ((this.GetRootGroupOperationCompleted == null)) {
                this.GetRootGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRootGroupOperationCompleted);
            }
            this.InvokeAsync("GetRootGroup", new object[0], this.GetRootGroupOperationCompleted, userState);
        }
        
        private void OnGetRootGroupOperationCompleted(object arg) {
            if ((this.GetRootGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRootGroupCompleted(this, new GetRootGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/SearchGroup", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SearchGroup(string groupName) {
            object[] results = this.Invoke("SearchGroup", new object[] {
                        groupName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchGroupAsync(string groupName) {
            this.SearchGroupAsync(groupName, null);
        }
        
        /// <remarks/>
        public void SearchGroupAsync(string groupName, object userState) {
            if ((this.SearchGroupOperationCompleted == null)) {
                this.SearchGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchGroupOperationCompleted);
            }
            this.InvokeAsync("SearchGroup", new object[] {
                        groupName}, this.SearchGroupOperationCompleted, userState);
        }
        
        private void OnSearchGroupOperationCompleted(object arg) {
            if ((this.SearchGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchGroupCompleted(this, new SearchGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetGroupList", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGroupList() {
            object[] results = this.Invoke("GetGroupList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupListAsync() {
            this.GetGroupListAsync(null);
        }
        
        /// <remarks/>
        public void GetGroupListAsync(object userState) {
            if ((this.GetGroupListOperationCompleted == null)) {
                this.GetGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupListOperationCompleted);
            }
            this.InvokeAsync("GetGroupList", new object[0], this.GetGroupListOperationCompleted, userState);
        }
        
        private void OnGetGroupListOperationCompleted(object arg) {
            if ((this.GetGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupListCompleted(this, new GetGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetUsersByGroupId", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUsersByGroupId(System.Guid groupId) {
            object[] results = this.Invoke("GetUsersByGroupId", new object[] {
                        groupId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByGroupIdAsync(System.Guid groupId) {
            this.GetUsersByGroupIdAsync(groupId, null);
        }
        
        /// <remarks/>
        public void GetUsersByGroupIdAsync(System.Guid groupId, object userState) {
            if ((this.GetUsersByGroupIdOperationCompleted == null)) {
                this.GetUsersByGroupIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByGroupIdOperationCompleted);
            }
            this.InvokeAsync("GetUsersByGroupId", new object[] {
                        groupId}, this.GetUsersByGroupIdOperationCompleted, userState);
        }
        
        private void OnGetUsersByGroupIdOperationCompleted(object arg) {
            if ((this.GetUsersByGroupIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByGroupIdCompleted(this, new GetUsersByGroupIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/SUSQL", RequestElementName="SUSQL", RequestNamespace="http://qjDataAccess.org/", ResponseElementName="SUSQLResponse", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SUSQLResult")]
        public System.Data.DataTable SearchUsers(string sqlWhere) {
            object[] results = this.Invoke("SearchUsers", new object[] {
                        sqlWhere});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchUsersAsync(string sqlWhere) {
            this.SearchUsersAsync(sqlWhere, null);
        }
        
        /// <remarks/>
        public void SearchUsersAsync(string sqlWhere, object userState) {
            if ((this.SearchUsersOperationCompleted == null)) {
                this.SearchUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchUsersOperationCompleted);
            }
            this.InvokeAsync("SearchUsers", new object[] {
                        sqlWhere}, this.SearchUsersOperationCompleted, userState);
        }
        
        private void OnSearchUsersOperationCompleted(object arg) {
            if ((this.SearchUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchUsersCompleted(this, new SearchUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchUsers1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/SUPARM", RequestElementName="SUPARM", RequestNamespace="http://qjDataAccess.org/", ResponseElementName="SUPARMResponse", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SUPARMResult")]
        public System.Data.DataTable SearchUsers(System.Guid groupid, string loginName, string userName) {
            object[] results = this.Invoke("SearchUsers1", new object[] {
                        groupid,
                        loginName,
                        userName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchUsers1Async(System.Guid groupid, string loginName, string userName) {
            this.SearchUsers1Async(groupid, loginName, userName, null);
        }
        
        /// <remarks/>
        public void SearchUsers1Async(System.Guid groupid, string loginName, string userName, object userState) {
            if ((this.SearchUsers1OperationCompleted == null)) {
                this.SearchUsers1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchUsers1OperationCompleted);
            }
            this.InvokeAsync("SearchUsers1", new object[] {
                        groupid,
                        loginName,
                        userName}, this.SearchUsers1OperationCompleted, userState);
        }
        
        private void OnSearchUsers1OperationCompleted(object arg) {
            if ((this.SearchUsers1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchUsers1Completed(this, new SearchUsers1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetGroupUsersStat", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGroupUsersStat() {
            object[] results = this.Invoke("GetGroupUsersStat", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupUsersStatAsync() {
            this.GetGroupUsersStatAsync(null);
        }
        
        /// <remarks/>
        public void GetGroupUsersStatAsync(object userState) {
            if ((this.GetGroupUsersStatOperationCompleted == null)) {
                this.GetGroupUsersStatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupUsersStatOperationCompleted);
            }
            this.InvokeAsync("GetGroupUsersStat", new object[0], this.GetGroupUsersStatOperationCompleted, userState);
        }
        
        private void OnGetGroupUsersStatOperationCompleted(object arg) {
            if ((this.GetGroupUsersStatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupUsersStatCompleted(this, new GetGroupUsersStatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetAllGroups", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllGroups(string spaceChar) {
            object[] results = this.Invoke("GetAllGroups", new object[] {
                        spaceChar});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllGroupsAsync(string spaceChar) {
            this.GetAllGroupsAsync(spaceChar, null);
        }
        
        /// <remarks/>
        public void GetAllGroupsAsync(string spaceChar, object userState) {
            if ((this.GetAllGroupsOperationCompleted == null)) {
                this.GetAllGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllGroupsOperationCompleted);
            }
            this.InvokeAsync("GetAllGroups", new object[] {
                        spaceChar}, this.GetAllGroupsOperationCompleted, userState);
        }
        
        private void OnGetAllGroupsOperationCompleted(object arg) {
            if ((this.GetAllGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllGroupsCompleted(this, new GetAllGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetGroupIdByGroupName", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetGroupIdByGroupName(string groupName) {
            object[] results = this.Invoke("GetGroupIdByGroupName", new object[] {
                        groupName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupIdByGroupNameAsync(string groupName) {
            this.GetGroupIdByGroupNameAsync(groupName, null);
        }
        
        /// <remarks/>
        public void GetGroupIdByGroupNameAsync(string groupName, object userState) {
            if ((this.GetGroupIdByGroupNameOperationCompleted == null)) {
                this.GetGroupIdByGroupNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupIdByGroupNameOperationCompleted);
            }
            this.InvokeAsync("GetGroupIdByGroupName", new object[] {
                        groupName}, this.GetGroupIdByGroupNameOperationCompleted, userState);
        }
        
        private void OnGetGroupIdByGroupNameOperationCompleted(object arg) {
            if ((this.GetGroupIdByGroupNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupIdByGroupNameCompleted(this, new GetGroupIdByGroupNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGroupCompletedEventHandler(object sender, GetGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateGroupCompletedEventHandler(object sender, CreateGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateChildGroupCompletedEventHandler(object sender, CreateChildGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateChildGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateChildGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteGroupCompletedEventHandler(object sender, DeleteGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModifyGroupCompletedEventHandler(object sender, ModifyGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTopGroupCompletedEventHandler(object sender, GetTopGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetChildGroupCompletedEventHandler(object sender, GetChildGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRootGroupCompletedEventHandler(object sender, GetRootGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRootGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRootGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchGroupCompletedEventHandler(object sender, SearchGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGroupListCompletedEventHandler(object sender, GetGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsersByGroupIdCompletedEventHandler(object sender, GetUsersByGroupIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByGroupIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByGroupIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchUsersCompletedEventHandler(object sender, SearchUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchUsers1CompletedEventHandler(object sender, SearchUsers1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchUsers1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchUsers1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGroupUsersStatCompletedEventHandler(object sender, GetGroupUsersStatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupUsersStatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupUsersStatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllGroupsCompletedEventHandler(object sender, GetAllGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGroupIdByGroupNameCompletedEventHandler(object sender, GetGroupIdByGroupNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupIdByGroupNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupIdByGroupNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591