//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.239 版自动生成。
// 
#pragma warning disable 1591

namespace QJVRMS.Business.BaseInfoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BaseInfoServiceSoap", Namespace="http://qjDataAccess.org/")]
    public partial class BaseInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSourceTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSourceBySourceIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsageTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUsageByUsageIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUsageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUsageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BaseInfoService() {
            this.Url = global::QJVRMS.Business.Properties.Settings.Default.QJVRMS_Business_BaseInfoWS_BaseInfoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSourceTableCompletedEventHandler GetSourceTableCompleted;
        
        /// <remarks/>
        public event DeleteSourceBySourceIDCompletedEventHandler DeleteSourceBySourceIDCompleted;
        
        /// <remarks/>
        public event UpdateSourceCompletedEventHandler UpdateSourceCompleted;
        
        /// <remarks/>
        public event AddSourceCompletedEventHandler AddSourceCompleted;
        
        /// <remarks/>
        public event GetUsageTableCompletedEventHandler GetUsageTableCompleted;
        
        /// <remarks/>
        public event DeleteUsageByUsageIDCompletedEventHandler DeleteUsageByUsageIDCompleted;
        
        /// <remarks/>
        public event UpdateUsageCompletedEventHandler UpdateUsageCompleted;
        
        /// <remarks/>
        public event AddUsageCompletedEventHandler AddUsageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetSourceTable", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSourceTable() {
            object[] results = this.Invoke("GetSourceTable", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSourceTableAsync() {
            this.GetSourceTableAsync(null);
        }
        
        /// <remarks/>
        public void GetSourceTableAsync(object userState) {
            if ((this.GetSourceTableOperationCompleted == null)) {
                this.GetSourceTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSourceTableOperationCompleted);
            }
            this.InvokeAsync("GetSourceTable", new object[0], this.GetSourceTableOperationCompleted, userState);
        }
        
        private void OnGetSourceTableOperationCompleted(object arg) {
            if ((this.GetSourceTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSourceTableCompleted(this, new GetSourceTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/DeleteSourceBySourceID", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteSourceBySourceID(int SourceID) {
            object[] results = this.Invoke("DeleteSourceBySourceID", new object[] {
                        SourceID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSourceBySourceIDAsync(int SourceID) {
            this.DeleteSourceBySourceIDAsync(SourceID, null);
        }
        
        /// <remarks/>
        public void DeleteSourceBySourceIDAsync(int SourceID, object userState) {
            if ((this.DeleteSourceBySourceIDOperationCompleted == null)) {
                this.DeleteSourceBySourceIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSourceBySourceIDOperationCompleted);
            }
            this.InvokeAsync("DeleteSourceBySourceID", new object[] {
                        SourceID}, this.DeleteSourceBySourceIDOperationCompleted, userState);
        }
        
        private void OnDeleteSourceBySourceIDOperationCompleted(object arg) {
            if ((this.DeleteSourceBySourceIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSourceBySourceIDCompleted(this, new DeleteSourceBySourceIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/UpdateSource", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateSource(int sourceId, string sourceName, string desc) {
            object[] results = this.Invoke("UpdateSource", new object[] {
                        sourceId,
                        sourceName,
                        desc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSourceAsync(int sourceId, string sourceName, string desc) {
            this.UpdateSourceAsync(sourceId, sourceName, desc, null);
        }
        
        /// <remarks/>
        public void UpdateSourceAsync(int sourceId, string sourceName, string desc, object userState) {
            if ((this.UpdateSourceOperationCompleted == null)) {
                this.UpdateSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSourceOperationCompleted);
            }
            this.InvokeAsync("UpdateSource", new object[] {
                        sourceId,
                        sourceName,
                        desc}, this.UpdateSourceOperationCompleted, userState);
        }
        
        private void OnUpdateSourceOperationCompleted(object arg) {
            if ((this.UpdateSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSourceCompleted(this, new UpdateSourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/AddSource", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddSource(string sourceName, string desc) {
            object[] results = this.Invoke("AddSource", new object[] {
                        sourceName,
                        desc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddSourceAsync(string sourceName, string desc) {
            this.AddSourceAsync(sourceName, desc, null);
        }
        
        /// <remarks/>
        public void AddSourceAsync(string sourceName, string desc, object userState) {
            if ((this.AddSourceOperationCompleted == null)) {
                this.AddSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSourceOperationCompleted);
            }
            this.InvokeAsync("AddSource", new object[] {
                        sourceName,
                        desc}, this.AddSourceOperationCompleted, userState);
        }
        
        private void OnAddSourceOperationCompleted(object arg) {
            if ((this.AddSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSourceCompleted(this, new AddSourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/GetUsageTable", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUsageTable() {
            object[] results = this.Invoke("GetUsageTable", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsageTableAsync() {
            this.GetUsageTableAsync(null);
        }
        
        /// <remarks/>
        public void GetUsageTableAsync(object userState) {
            if ((this.GetUsageTableOperationCompleted == null)) {
                this.GetUsageTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsageTableOperationCompleted);
            }
            this.InvokeAsync("GetUsageTable", new object[0], this.GetUsageTableOperationCompleted, userState);
        }
        
        private void OnGetUsageTableOperationCompleted(object arg) {
            if ((this.GetUsageTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsageTableCompleted(this, new GetUsageTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/DeleteUsageByUsageID", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUsageByUsageID(int UsageID) {
            object[] results = this.Invoke("DeleteUsageByUsageID", new object[] {
                        UsageID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUsageByUsageIDAsync(int UsageID) {
            this.DeleteUsageByUsageIDAsync(UsageID, null);
        }
        
        /// <remarks/>
        public void DeleteUsageByUsageIDAsync(int UsageID, object userState) {
            if ((this.DeleteUsageByUsageIDOperationCompleted == null)) {
                this.DeleteUsageByUsageIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUsageByUsageIDOperationCompleted);
            }
            this.InvokeAsync("DeleteUsageByUsageID", new object[] {
                        UsageID}, this.DeleteUsageByUsageIDOperationCompleted, userState);
        }
        
        private void OnDeleteUsageByUsageIDOperationCompleted(object arg) {
            if ((this.DeleteUsageByUsageIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUsageByUsageIDCompleted(this, new DeleteUsageByUsageIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/UpdateUsage", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUsage(int usageId, string usageName, string desc) {
            object[] results = this.Invoke("UpdateUsage", new object[] {
                        usageId,
                        usageName,
                        desc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUsageAsync(int usageId, string usageName, string desc) {
            this.UpdateUsageAsync(usageId, usageName, desc, null);
        }
        
        /// <remarks/>
        public void UpdateUsageAsync(int usageId, string usageName, string desc, object userState) {
            if ((this.UpdateUsageOperationCompleted == null)) {
                this.UpdateUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUsageOperationCompleted);
            }
            this.InvokeAsync("UpdateUsage", new object[] {
                        usageId,
                        usageName,
                        desc}, this.UpdateUsageOperationCompleted, userState);
        }
        
        private void OnUpdateUsageOperationCompleted(object arg) {
            if ((this.UpdateUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUsageCompleted(this, new UpdateUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qjDataAccess.org/AddUsage", RequestNamespace="http://qjDataAccess.org/", ResponseNamespace="http://qjDataAccess.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddUsage(string usageName, string desc) {
            object[] results = this.Invoke("AddUsage", new object[] {
                        usageName,
                        desc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddUsageAsync(string usageName, string desc) {
            this.AddUsageAsync(usageName, desc, null);
        }
        
        /// <remarks/>
        public void AddUsageAsync(string usageName, string desc, object userState) {
            if ((this.AddUsageOperationCompleted == null)) {
                this.AddUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUsageOperationCompleted);
            }
            this.InvokeAsync("AddUsage", new object[] {
                        usageName,
                        desc}, this.AddUsageOperationCompleted, userState);
        }
        
        private void OnAddUsageOperationCompleted(object arg) {
            if ((this.AddUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUsageCompleted(this, new AddUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSourceTableCompletedEventHandler(object sender, GetSourceTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSourceTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSourceTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteSourceBySourceIDCompletedEventHandler(object sender, DeleteSourceBySourceIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSourceBySourceIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSourceBySourceIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateSourceCompletedEventHandler(object sender, UpdateSourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddSourceCompletedEventHandler(object sender, AddSourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsageTableCompletedEventHandler(object sender, GetUsageTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsageTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsageTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteUsageByUsageIDCompletedEventHandler(object sender, DeleteUsageByUsageIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUsageByUsageIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUsageByUsageIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateUsageCompletedEventHandler(object sender, UpdateUsageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddUsageCompletedEventHandler(object sender, AddUsageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591